refactor: Simplify entrypoint

diff --git a/misc/entrypoint b/misc/entrypoint
--- a/misc/entrypoint
+++ b/misc/entrypoint
@@ -19,7 +19,14 @@ set -euo pipefail
 # path. We do this by searching for the mountpoint of type `bind` (not `volume`, as
 # that's what Docker uses when the volume was omitted) and that starts with `/main`.
 MOUNTS=$(docker inspect "$HOSTNAME" -f '{{range .Mounts }}{{ .Type }} {{ .Destination }} {{ .Source }}{{ printf "\n" }}{{ end }}')
-echo "$MOUNTS" | awk '/^bind \/main/ {print "HARBORMASTER_HOST_DATA=" $3}' > /root/project_env.sh
+HOST_MOUNT=$(echo "$MOUNTS" | awk '/^bind \/main/ {print $3}')
+
+if [ -n "$HOST_MOUNT" ]; then
+    echo "HARBORMASTER_HOST_DATA=$HOST_MOUNT" > /root/project_env.sh
+else
+    echo "Harbormaster error: /main volume not mounted properly, cannot continue."
+    exit 1
+fi
 
 # Run Harbormaster once before starting cron, because cron waits until it's time before
 # it actually runs anything, which is bad UX.
